// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://risuhucghwkigqararqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpc3VodWNnaHdraWdxYXJhcnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzUyMjgsImV4cCI6MjA3MDAxMTIyOH0.ca4_kCBYVgV1Mu1VEUs7CYmNPdVvQnLIwJM4gOr9_0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});